import bs4
import requests
import csv

def function1():

    base_url = "https://www.dainikamadershomoy.com/archive"
    catagory = "sports"
    #next_page = "18"

    national_catagory = [""]

    all_url = []
    i=0
    for page_index in national_catagory:
        i=i+1
        if i==1:
            complete_url =  base_url + '/' + catagory + '/'#+ next_page + '/'
            #print(complete_url + '18')
            #print(complete_url + '36')
        else:
            complete_url = base_url + '/' + catagory + '/' +str(page_index)
            #print(complete_url + '18')
            #print(complete_url + '36')
        all_url.append([complete_url])
        all_url.append([complete_url+'20'])
        all_url.append([complete_url + '40'])
        all_url.append([complete_url + '60'])
        all_url.append([complete_url + '80'])
        all_url.append([complete_url + '100'])
        all_url.append([complete_url + '120'])
        all_url.append([complete_url + '140'])
        all_url.append([complete_url + '160'])
        all_url.append([complete_url + '180'])
        all_url.append([complete_url + '200'])
        all_url.append([complete_url + '220'])
        all_url.append([complete_url + '240'])
        all_url.append([complete_url + '260'])
        all_url.append([complete_url + '280'])
        all_url.append([complete_url + '300'])
        all_url.append([complete_url + '320'])
        all_url.append([complete_url + '340'])
        all_url.append([complete_url + '360'])
        all_url.append([complete_url + '380'])
        all_url.append([complete_url + '400'])
        all_url.append([complete_url + '420'])
        all_url.append([complete_url + '440'])
        all_url.append([complete_url + '460'])
        all_url.append([complete_url + '480'])
        all_url.append([complete_url + '500'])
        all_url.append([complete_url + '520'])
        all_url.append([complete_url + '540'])
        all_url.append([complete_url + '560'])
        all_url.append([complete_url + '580'])
        all_url.append([complete_url + '600'])
        all_url.append([complete_url + '620'])
        all_url.append([complete_url + '640'])
        all_url.append([complete_url + '660'])
        all_url.append([complete_url + '680'])
        all_url.append([complete_url + '700'])
        all_url.append([complete_url + '720'])
        all_url.append([complete_url + '740'])
        all_url.append([complete_url + '760'])
        all_url.append([complete_url + '780'])
        all_url.append([complete_url + '800'])
        all_url.append([complete_url + '820'])
        all_url.append([complete_url + '840'])
        all_url.append([complete_url + '860'])
        all_url.append([complete_url + '880'])
        all_url.append([complete_url + '900'])
        all_url.append([complete_url + '920'])
        all_url.append([complete_url + '940'])
        all_url.append([complete_url + '960'])
        all_url.append([complete_url + '980'])
        all_url.append([complete_url + '1000'])
        all_url.append([complete_url + '1020'])
        all_url.append([complete_url + '1040'])
        all_url.append([complete_url + '1060'])
        all_url.append([complete_url + '1080'])
        all_url.append([complete_url + '1100'])
        all_url.append([complete_url + '1120'])
        all_url.append([complete_url + '1140'])
        all_url.append([complete_url + '1160'])
        all_url.append([complete_url + '1180'])
        all_url.append([complete_url + '1200'])
        all_url.append([complete_url + '1220'])
        all_url.append([complete_url + '1240'])
        all_url.append([complete_url + '1260'])
        all_url.append([complete_url + '1280'])
        all_url.append([complete_url + '1300'])
        all_url.append([complete_url + '1320'])
        all_url.append([complete_url + '1340'])
        all_url.append([complete_url + '1360'])
        all_url.append([complete_url + '1380'])
        all_url.append([complete_url + '1400'])
        all_url.append([complete_url + '1420'])
        all_url.append([complete_url + '1440'])
        all_url.append([complete_url + '1460'])
        all_url.append([complete_url + '1480'])
        all_url.append([complete_url + '1500'])
        all_url.append([complete_url + '1520'])
        all_url.append([complete_url + '1540'])
        all_url.append([complete_url + '1560'])
        all_url.append([complete_url + '1580'])
        all_url.append([complete_url + '1600'])
        all_url.append([complete_url + '1620'])
        all_url.append([complete_url + '1640'])
        all_url.append([complete_url + '1660'])
        all_url.append([complete_url + '1680'])
        all_url.append([complete_url + '1700'])
        all_url.append([complete_url + '1720'])
        all_url.append([complete_url + '1740'])
        all_url.append([complete_url + '1760'])
        all_url.append([complete_url + '1780'])
        all_url.append([complete_url + '1800'])
        all_url.append([complete_url + '1820'])
        all_url.append([complete_url + '1840'])
        all_url.append([complete_url + '1860'])
        all_url.append([complete_url + '1880'])
        all_url.append([complete_url + '1900'])
        all_url.append([complete_url + '1920'])
        all_url.append([complete_url + '1940'])
        all_url.append([complete_url + '1960'])
        all_url.append([complete_url + '1980'])
        all_url.append([complete_url + '2000'])
        all_url.append([complete_url + '2020'])
        all_url.append([complete_url + '2040'])
        all_url.append([complete_url + '2060'])
        all_url.append([complete_url + '2080'])
        all_url.append([complete_url + '2100'])
        all_url.append([complete_url + '2120'])
        all_url.append([complete_url + '2140'])
        all_url.append([complete_url + '2160'])
        all_url.append([complete_url + '2180'])
        all_url.append([complete_url + '2200'])
        all_url.append([complete_url + '2220'])
        all_url.append([complete_url + '2240'])
        all_url.append([complete_url + '2260'])
        all_url.append([complete_url + '2280'])
        all_url.append([complete_url + '2300'])
        all_url.append([complete_url + '2320'])
        all_url.append([complete_url + '2340'])
        all_url.append([complete_url + '2360'])
        all_url.append([complete_url + '2380'])
        all_url.append([complete_url + '2400'])
        all_url.append([complete_url + '2420'])
        all_url.append([complete_url + '2440'])
        all_url.append([complete_url + '2460'])
        all_url.append([complete_url + '2480'])
        all_url.append([complete_url + '2500'])
        all_url.append([complete_url + '2520'])
        all_url.append([complete_url + '2540'])
        all_url.append([complete_url + '2560'])
        all_url.append([complete_url + '2580'])
        all_url.append([complete_url + '2600'])
        all_url.append([complete_url + '2620'])
        all_url.append([complete_url + '2640'])
        all_url.append([complete_url + '2660'])
        all_url.append([complete_url + '2680'])
        all_url.append([complete_url + '2700'])
        all_url.append([complete_url + '2720'])
        all_url.append([complete_url + '2740'])
        all_url.append([complete_url + '2760'])
        all_url.append([complete_url + '2780'])
        all_url.append([complete_url + '2800'])
        all_url.append([complete_url + '2820'])
        all_url.append([complete_url + '2840'])
        all_url.append([complete_url + '2860'])
        all_url.append([complete_url + '2880'])
        all_url.append([complete_url + '2900'])
        all_url.append([complete_url + '2920'])
        all_url.append([complete_url + '2940'])
        all_url.append([complete_url + '2960'])
        all_url.append([complete_url + '2980'])
        all_url.append([complete_url + '3000'])
        all_url.append([complete_url + '3020'])
        all_url.append([complete_url + '3040'])
        all_url.append([complete_url + '3060'])
        all_url.append([complete_url + '3080'])
        all_url.append([complete_url + '3100'])
        all_url.append([complete_url + '3120'])
        all_url.append([complete_url + '3140'])
        all_url.append([complete_url + '3160'])
        all_url.append([complete_url + '3180'])
        all_url.append([complete_url + '3200'])
        all_url.append([complete_url + '3220'])
        all_url.append([complete_url + '3240'])
        all_url.append([complete_url + '3260'])
        all_url.append([complete_url + '3280'])
        all_url.append([complete_url + '3300'])
        all_url.append([complete_url + '3320'])
        all_url.append([complete_url + '3340'])
        all_url.append([complete_url + '3360'])
        all_url.append([complete_url + '3380'])
        all_url.append([complete_url + '3400'])
        all_url.append([complete_url + '3420'])
        all_url.append([complete_url + '3440'])
        all_url.append([complete_url + '3460'])
        all_url.append([complete_url + '3480'])
        all_url.append([complete_url + '3500'])
        all_url.append([complete_url + '3520'])
        all_url.append([complete_url + '3540'])
        all_url.append([complete_url + '3560'])
        all_url.append([complete_url + '3580'])
        all_url.append([complete_url + '3600'])
        all_url.append([complete_url + '3620'])
        all_url.append([complete_url + '3640'])
        all_url.append([complete_url + '3660'])
        all_url.append([complete_url + '3680'])
        all_url.append([complete_url + '3700'])
        all_url.append([complete_url + '3720'])
        all_url.append([complete_url + '3740'])
        all_url.append([complete_url + '3760'])
        all_url.append([complete_url + '3780'])
        all_url.append([complete_url + '3800'])
        all_url.append([complete_url + '3820'])
        all_url.append([complete_url + '3840'])
        all_url.append([complete_url + '3860'])
        all_url.append([complete_url + '3880'])
        all_url.append([complete_url + '3900'])
        all_url.append([complete_url + '3920'])
        all_url.append([complete_url + '3940'])
        all_url.append([complete_url + '3960'])
        all_url.append([complete_url + '3980'])
        all_url.append([complete_url + '4000'])
        all_url.append([complete_url + '4020'])
        all_url.append([complete_url + '4040'])
        all_url.append([complete_url + '4060'])
        all_url.append([complete_url + '4080'])
        all_url.append([complete_url + '4100'])
        all_url.append([complete_url + '4120'])
        all_url.append([complete_url + '4140'])
        all_url.append([complete_url + '4160'])
        all_url.append([complete_url + '4180'])
        all_url.append([complete_url + '4200'])
        all_url.append([complete_url + '4220'])
        all_url.append([complete_url + '4240'])
        all_url.append([complete_url + '4260'])
        all_url.append([complete_url + '4280'])
        all_url.append([complete_url + '4300'])
        all_url.append([complete_url + '4320'])
        all_url.append([complete_url + '4340'])
        all_url.append([complete_url + '4360'])
        all_url.append([complete_url + '4380'])
        all_url.append([complete_url + '4400'])
        all_url.append([complete_url + '4420'])
        all_url.append([complete_url + '4440'])
        all_url.append([complete_url + '4460'])
        all_url.append([complete_url + '4480'])
        all_url.append([complete_url + '4500'])
        all_url.append([complete_url + '4520'])
        all_url.append([complete_url + '4440'])
        all_url.append([complete_url + '4460'])
        all_url.append([complete_url + '4480'])
        all_url.append([complete_url + '4500'])








    with open('main_page_url.csv',mode = 'w', newline='') as main_url_list:
        main_url_writer = csv.writer(main_url_list,delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

        for url in all_url:
            print(url)
            main_url_writer.writerow(url)

    main_url_list.close()
    return all_url
function1()
